;;;;;;;;;;;;;;;;;;;;;
; FPM Configuration ;
;;;;;;;;;;;;;;;;;;;;;

[global]

; Log de erros do PHP-FPM
error_log = /proc/self/fd/2

; Define o nível de log (menos logs para produção)
log_level = warning

; Define o máximo de processos do FPM (evita sobrecarga)
process.max = 200

; Define prioridade dos processos (melhor performance)
;process.priority = -10

; Defina o mecanismo de eventos para melhor eficiência (Linux: epoll)
events.mechanism = epoll

; Define tempo máximo antes de reiniciar o FPM (previne memória corrompida)
emergency_restart_interval = 1m
emergency_restart_threshold = 10
process_control_timeout = 10s

; Define um limite maior para arquivos abertos
rlimit_files = 65536
rlimit_core = unlimited

;;;;;;;;;;;;;;;;;;;;
; Pool Definitions ;
;;;;;;;;;;;;;;;;;;;;

include=etc/php-fpm.d/*.conf
include=etc/php-fpm.d/sites-enabled/*.conf
