[global]
daemonize   = no
error_log = /proc/self/fd/2

[www]
; Define o usuário e grupo dos processos
user  = 1000
group = 1000

listen = 9001

pm = dynamic
pm.max_children = 50            ; Aumentado para suportar mais requisições simultâneas
pm.start_servers = 10           ; Número inicial maior para melhor resposta ao tráfego
pm.min_spare_servers = 5        ; Mais processos ociosos para evitar latência
pm.max_spare_servers = 15       ; Permite mais processos ociosos antes de serem removidos
pm.process_idle_timeout = 15s   ; Fecha processos ociosos mais rapidamente
pm.max_requests = 2000          ; Reduzido para evitar vazamento de memória

request_terminate_timeout = 3600s

;request_slowlog_timeout = 10s
;slowlog = /var/log/php-fpm-slow.log

rlimit_files = 65536
rlimit_core = unlimited
